### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by seanpringle** [nci/geocrawler#1]
- [x] include lat/long polygon
  - check himawari
- [x] check himawari nulls
- [x] simplify/remove compact
- [ ] review proj4 text to try to avoid error on ST_Transform fail

**Comment by monkeybutter** [comment]
Closed with commit 
[4617fc105737fa2e0d2acd737bbdab3872e67620](https://github.com/nci/geocrawler/commit/4617fc105737fa2e0d2acd737bbdab3872e67620)
